services:
  - type: web
    name: valentine-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python phonever.py
    envVars:
      - key: FLASK_ENV
        value: production
